In [ ]:
print("Antas")

Antas

In [ ]:
import pandas as pd
df = pd.read_csv("/content/df_use_csv.csv")
df

,genre_ids,overview,title
0,"[18, 80]",Imprisoned in the 1940s for the double murder ...,The Shawshank Redemption
1,"[18, 80]","Spanning the years 1945 to 1955, a chronicle o...",The Godfather
2,"[18, 80]",In the continuing saga of the Corleone crime f...,The Godfather Part II
3,"[18, 36, 10752]",The true story of how businessman Oskar Schind...,Schindler's List
4,[18],The defense and the prosecution have rested an...,12 Angry Men
...,...,...,...
195,[18],Crotchety retired doctor Isak Borg travels fro...,Wild Strawberries
196,"[878, 18, 10749]","Joel Barish, heartbroken that his girlfriend u...",Eternal Sunshine of the Spotless Mind
197,"[16, 18, 14]",Found inside a shining stalk of bamboo by an o...,The Tale of The Princess Kaguya
198,"[35, 80]","Best friends Peppe and Mario are thieves, but ...",Big Deal on Madonna Street
199,"[16, 10770, 14, 28]","Marinette’s class is headed to New York, the c...","Miraculous World: New York, United HeroeZ"

In [ ]:
#lowering the chars
df['overview'] = df['overview'].str.lower()
df

,genre_ids,overview,title
0,"[18, 80]",imprisoned in the 1940s for the double murder ...,The Shawshank Redemption
1,"[18, 80]","spanning the years 1945 to 1955, a chronicle o...",The Godfather
2,"[18, 80]",in the continuing saga of the corleone crime f...,The Godfather Part II
3,"[18, 36, 10752]",the true story of how businessman oskar schind...,Schindler's List
4,[18],the defense and the prosecution have rested an...,12 Angry Men
...,...,...,...
195,[18],crotchety retired doctor isak borg travels fro...,Wild Strawberries
196,"[878, 18, 10749]","joel barish, heartbroken that his girlfriend u...",Eternal Sunshine of the Spotless Mind
197,"[16, 18, 14]",found inside a shining stalk of bamboo by an o...,The Tale of The Princess Kaguya
198,"[35, 80]","best friends peppe and mario are thieves, but ...",Big Deal on Madonna Street
199,"[16, 10770, 14, 28]","marinette’s class is headed to new york, the c...","Miraculous World: New York, United HeroeZ"

In [ ]:
import string, time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def remove_punctuation(text):
  return text.translate(str.maketrans('','',string.punctuation))

In [ ]:
df['overview'] = df['overview'].apply(lambda text: remove_punctuation(text))
df

,genre_ids,overview,title
0,"[18, 80]",imprisoned in the 1940s for the double murder ...,The Shawshank Redemption
1,"[18, 80]",spanning the years 1945 to 1955 a chronicle of...,The Godfather
2,"[18, 80]",in the continuing saga of the corleone crime f...,The Godfather Part II
3,"[18, 36, 10752]",the true story of how businessman oskar schind...,Schindler's List
4,[18],the defense and the prosecution have rested an...,12 Angry Men
...,...,...,...
195,[18],crotchety retired doctor isak borg travels fro...,Wild Strawberries
196,"[878, 18, 10749]",joel barish heartbroken that his girlfriend un...,Eternal Sunshine of the Spotless Mind
197,"[16, 18, 14]",found inside a shining stalk of bamboo by an o...,The Tale of The Princess Kaguya
198,"[35, 80]",best friends peppe and mario are thieves but t...,Big Deal on Madonna Street
199,"[16, 10770, 14, 28]",marinette’s class is headed to new york the ci...,"Miraculous World: New York, United HeroeZ"

In [ ]:
df['overview'][3]

'the true story of how businessman oskar schindler saved over a thousand jewish lives from the nazis while they worked as slaves in his factory during world war ii'

In [ ]:
from textblob import TextBlob

def Correct_spelling(text):
  return str(TextBlob(text).correct())

In [ ]:
df['overview'] = df['overview'].apply(lambda text: Correct_spelling(text))
df

,genre_ids,overview,title
0,"[18, 80]",imprisoned in the 1940s for the double murder ...,The Shawshank Redemption
1,"[18, 80]",spanning the years 1945 to 1955 a chronicle of...,The Godfather
2,"[18, 80]",in the continuing sage of the corleone crime f...,The Godfather Part II
3,"[18, 36, 10752]",the true story of how businessman oscar schind...,Schindler's List
4,[18],the defense and the prosecution have rested an...,12 Angry Men
...,...,...,...
195,[18],crotchety retired doctor isa berg travels from...,Wild Strawberries
196,"[878, 18, 10749]",joel parish heartbroken that his girlfriend un...,Eternal Sunshine of the Spotless Mind
197,"[16, 18, 14]",found inside a shining stalk of bamboo by an o...,The Tale of The Princess Kaguya
198,"[35, 80]",best friends pepper and marie are thieves but ...,Big Deal on Madonna Street
199,"[16, 10770, 14, 28]",marquette’s class is headed to new york the ci...,"Miraculous World: New York, United HeroeZ"

In [ ]:
df ['overview'][6]

'batman raises the stakes in his war on crime with the help of it jim gordon and district attorney harvey went batman sets out to dismantled the remaining criminal organizations that plague the streets the partnership proves to be effective but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastering known to the terrified citizens of gothic as the joke'

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stpw = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
print(stpw)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [ ]:
def remove_stpw(text):
  new_text =[]
  for word in text.split():
    if word in stpw:
      continue
    new_text.append(word)
  return " ".join(new_text)

In [ ]:
df['overview'] = df['overview'].apply(lambda text: remove_stpw(text))
df

,genre_ids,overview,title
0,"[18, 80]",imprisoned 1940s double murder wife lover stan...,The Shawshank Redemption
1,"[18, 80]",spanning years 1945 1955 chronicle sectional i...,The Godfather
2,"[18, 80]",continuing sage corleone crime family young ve...,The Godfather Part II
3,"[18, 36, 10752]",true story businessman oscar schindler saved t...,Schindler's List
4,[18],defense prosecution rested jury filing jury ro...,12 Angry Men
...,...,...,...
195,[18],crotchety retired doctor isa berg travels stoc...,Wild Strawberries
196,"[878, 18, 10749]",joel parish heartbroken girlfriend underwent p...,Eternal Sunshine of the Spotless Mind
197,"[16, 18, 14]",found inside shining stalk bamboo old bamboo u...,The Tale of The Princess Kaguya
198,"[35, 80]",best friends pepper marie thieves good still p...,Big Deal on Madonna Street
199,"[16, 10770, 14, 28]",marquette’s class headed new york city superhe...,"Miraculous World: New York, United HeroeZ"

In [ ]:
df['overview'][6]

'batman raises stakes war crime help jim gordon district attorney harvey went batman sets dismantled remaining criminal organizations plague streets partnership proves effective soon find prey reign chaos unleashed rising criminal mastering known terrified citizens gothic joke'

In [ ]:
from nltk.tokenize import word_tokenize
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
df['overview'] = df['overview'].apply(lambda text: word_tokenize(text))

In [ ]:
df['overview'][6]

['batman',
 'raises',
 'stakes',
 'war',
 'crime',
 'help',
 'jim',
 'gordon',
 'district',
 'attorney',
 'harvey',
 'went',
 'batman',
 'sets',
 'dismantled',
 'remaining',
 'criminal',
 'organizations',
 'plague',
 'streets',
 'partnership',
 'proves',
 'effective',
 'soon',
 'find',
 'prey',
 'reign',
 'chaos',
 'unleashed',
 'rising',
 'criminal',
 'mastering',
 'known',
 'terrified',
 'citizens',
 'gothic',
 'joke']

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [ ]:
Lemmatizer = WordNetLemmatizer()

def lemitize(tokenise_list):
  new_text = []
  for word in tokenise_list:
    new_text.append(Lemmatizer.lemmatize(word, pos ='v'))
  return new_text

In [ ]:
df['overview'] = df['overview'].apply(lambda text: lemitize(text))
df['overview'][6]

['batman',
 'raise',
 'stake',
 'war',
 'crime',
 'help',
 'jim',
 'gordon',
 'district',
 'attorney',
 'harvey',
 'go',
 'batman',
 'set',
 'dismantle',
 'remain',
 'criminal',
 'organizations',
 'plague',
 'streets',
 'partnership',
 'prove',
 'effective',
 'soon',
 'find',
 'prey',
 'reign',
 'chaos',
 'unleash',
 'rise',
 'criminal',
 'master',
 'know',
 'terrify',
 'citizens',
 'gothic',
 'joke']

In [ ]:
df.to_csv('text_preprocessed.csv', index= False)